# Generated by Django 5.1.3 on 2024-12-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='spot',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spotimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spot_images/'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
